### ISSUE TITLE
nodes.yaml is missing?

### ISSUE THREAD

**Issue by susu3621** [Photogrammetry-Robotics-Bonn/bonnet#5]
This project is very attractive! But when I tried it, the nodes.yaml seems missing.
Is this file missed?

I'm using the pre-trained model: cityspaces 512x256 and 1024x512

log:
Successfully created log directory: log
Unable to create network.
Invalid yaml file city_512/nodes.yaml

**Comment by tano297** [comment]
Hello,

The reason why it is missing is because the folder provided is a log folder, and in the case you are using you need the frozen model. This is done this way by design, as the "nodes.yaml" is only necessary when using a frozen model, and its contents can be automatically generated to reduce user input. 

To learn how to freeze the log folder, please refer to the python section of the readme! 

Let me know if you need further help, otherwise I will close this issue.

Thanks!

**Comment by susu3621** [comment]
Thanks for your quick reply.
Have confirmed the code works perfect after I freeze the model.
Thanks a lot. I close this issue.

**Comment by tano297** [comment]
I can freeze some for you if you tell me which, but the idea of keeping the logs separate from the frozen models is that as we add backends, or if we do specific optimizations to the graph during freezing and then the backends change, the frozen models break. 

I strongly recommend you give the docker container a look, it contains all the dependencies, so it should be a matter of minutes to get the freezing going.

**Comment by mfe7** [comment]
@tano297 Thanks for that suggestion. I'll try out the docker

**Comment by chenyumingx** [comment]
I have encountered the same problem,"Invalid yaml file persons_512/nodes.yaml"
but I do not fully understand your answer, and **do not know how to solve it**. Can you answer in more details? Thank you very much!

**Comment by AI-liu** [comment]
export PYTHONPATH=/usr/local/lib/python3.6/site-packages/cv2:$PYTHONPATH
python3 cnn_freeze.py -p /tmp/path/to/pretrained -l  /tmp/path/to/log

maybe you missed  -l  /tmp/path/to/log
